import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../styles/globals.css";

import { TrpcProvider } from "@/app/_components/TrpcProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <TrpcProvider>
      <html className="inter.className">
        <body>{children}</body>
      </html>
    </TrpcProvider>
  );
}
