import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../styles/globals.css";

import type { AppType } from "next/app";
import { trpc } from "../utils/trpc";
import { TrpcProvider } from "@/app/_components/TrpcProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

// const MyApp: AppType = ({ Component, pageProps }) => {
//   // return <Component {...pageProps} />;

//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Component {...pageProps} />
//       </body>
//     </html>
//   );
// };

// export default trpc.withTRPC(MyApp);

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <TrpcProvider>
      <html className="inter.className">
        <body>{children}</body>
      </html>
    </TrpcProvider>
  );
}
